version: "3.9"
services:
  front:
    image: wolframowy/pf2lootgen_frontend
    platform: linux/arm/v7
    build: 
      context: .
      dockerfile: docker/front/dockerfile
    ports:
      - "3000:3000"
  back:
    image: wolframowy/pf2lootgen_backend
    platform: linux/arm/v7
    build: 
      context: .
      dockerfile: docker/back/dockerfile
    ports:
      - "5000:5000"
