services:
  front:
    image: wolframowy/pf2lootgen_frontend
    platform: linux/arm/v7
    build: 
      context: .
      dockerfile: docker/front/dockerfile
      args:
        - REACT_APP_SERVER_URL=http://pokierejszowany.mooo.com:5000/api
    ports:
      - "3000:3000"
    restart: always
  back:
    image: wolframowy/pf2lootgen_backend
    platform: linux/arm/v7
    build: 
      context: .
      dockerfile: docker/back/dockerfile
    ports:
      - "5000:5000"
    restart: always
    volumes:
      - ./db:/app/db
