FROM python:alpine

WORKDIR /app
COPY db db
COPY python python
RUN pip3 install gunicorn
RUN pip3 install --no-cache-dir -r ./python/req_server.txt

WORKDIR /app/python
EXPOSE 5000
ENTRYPOINT [ "gunicorn", "-b", "0.0.0.0:5000", \
                      "-w", "4", \
                      "server:app"]
